### ISSUE TITLE
Adding a CFNType variable to a blueprint with no value breaks

### ISSUE THREAD

**Issue by ejholmes** [cloudtools/stacker#457]
Given you have a blueprint with no variables that's already been deployed, if you add a variable that uses a CFNType, and don't specify a value for it in `stacker.yaml`, then updating the stack will fail:

```
Parameter validation failed: parameter value for parameter name XXX does not exist
```

**Comment by phobologic** [comment]
Iiiinteresting. It probably happens when it goes to lookup the previous value.  Should be an easy fix.

**Comment by phobologic** [comment]
Ok, with these two blueprints:

```
# cat blueprints/__init__.py
from troposphere import Output, Ref

from troposphere.cloudformation import WaitConditionHandle

from stacker.blueprints.base import Blueprint
from stacker.blueprints.variables.types import CFNString


class Dummy(Blueprint):
    VARIABLES = {
        "Name": {
            "type": CFNString,
            "description": "A string.",
        }
    }

    def create_template(self):
        self.template.add_resource(WaitConditionHandle("Dummy"))
        self.template.add_output(Output("DummyId", Value="dummy-1234"))
        self.template.add_output(Output("Region", Value=Ref("AWS::Region")))
        self.template.add_output(Output("Name", Value=Ref("Name")))


class Dummy2(Blueprint):
    def create_template(self):
        self.template.add_resource(WaitConditionHandle("Dummy"))
        self.template.add_output(Output("DummyId", Value="dummy-1234"))
        self.template.add_output(Output("Region", Value=Ref("AWS::Region")))
```

And using this config & env:

```
# cat dev.env
namespace: stacker-test-namespace

# cat stacker.yml
namespace: ${namespace}

sys_path: .

stacks:
  - name: vpc
    class_path: blueprints.Dummy
```

If I switch the class_path from Dummy2 to Dummy1 without providing the `Name` variable, I now get this error, which seems correct:

```
# stacker build --region us-east-1 ./dev.env ./stacker.yml
[2018-05-27T15:05:09] Using default AWS provider mode
[2018-05-27T15:05:10] Variable "Name" in blueprint "vpc" is missing
Traceback (most recent call last):
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/plan.py", line 89, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/actions/build.py", line 279, in _launch_stack
    stack.resolve(self.context, self.provider)
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/stack.py", line 187, in resolve
    self.blueprint.resolve_variables(self.variables)
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/blueprints/base.py", line 445, in resolve_variables
    self.name
  File "/Users/mike/venv/stest/lib/python2.7/site-packages/stacker/blueprints/base.py", line 209, in resolve_variable
    raise MissingVariable(blueprint_name, var_name)
MissingVariable: Variable "Name" in blueprint "vpc" is missing
[2018-05-27T15:05:10] vpc: failed (Variable "Name" in blueprint "vpc" is missing)
[2018-05-27T15:05:10] The following steps failed: vpc
```

Going to close this - if this doesn't seem right, go ahead and re-open it @ejholmes
