### ISSUE TITLE
How to render a CloudFormation template without building it and without issuing any requests to AWS?

### ISSUE THREAD

**Issue by behrangsa** [cloudtools/stacker#621]
Executing:

    $ stacker build -d DUMP -v -o my-config.yml

fails due to:

    botocore.exceptions.ClientError: An error occurred (400) when calling HeadBucket operation: Bad Request

Is there a way to dump the CloudFormation template locally without any interactions with AWS?

**Comment by behrangsa** [comment]
Looks like only setting the `stacker_bucket` to `""` can skip uploading the template to S3. It would be great if there was a command line option to _only_ dump the template.

**Comment by ejholmes** [comment]
This is actually kinda surprising. When `--dump` is specific, stacker shouldn't be making a `HeadBucket` request: 

https://github.com/cloudtools/stacker/blob/28e2a228647c4a8fb11f7a229eb006b9bd16afa8/stacker/actions/build.py#L77-L88

**Comment by behrangsa** [comment]
Here's the output:

```
$ stacker build -d DUMP -o my-config.yml
[2018-07-06T14:53:50] Using default AWS provider mode
[2018-07-06T14:53:53] Error creating bucket stacker-foo. Error {'ResponseMetadata': {'HTTPStatusCode': 400, 'RetryAttempts': 1, 'HostId': '...=', 'RequestId': '4E4...6B7', 'HTTPHeaders': {'date': 'Fri, 06 Jul 2018 04:53:53 GMT', 'x-amz-id-2': '...=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': '4E4...6B7', 'x-amz-bucket-region': 'us-east-1', 'content-type': 'application/xml'}}, 'Error': {'Message': 'Bad Request', 'Code': '400'}}
Traceback (most recent call last):
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/stacker/util.py", line 476, in ensure_s3_bucket
    s3_client.head_bucket(Bucket=bucket_name)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (400) when calling the HeadBucket operation: Bad Request
Traceback (most recent call last):
  File "/Users/behrang/.virtualenvs/stacker-venv/bin/stacker", line 10, in <module>
    args.run(args)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/stacker/commands/stacker/build.py", line 55, in run
    dump=options.dump)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/stacker/actions/base.py", line 184, in execute
    self.pre_run(*args, **kwargs)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/stacker/actions/build.py", line 354, in pre_run
    self.ensure_cfn_bucket()
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/stacker/actions/base.py", line 144, in ensure_cfn_bucket
    self.bucket_region)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/stacker/util.py", line 476, in ensure_s3_bucket
    s3_client.head_bucket(Bucket=bucket_name)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/behrang/.virtualenvs/stacker-venv/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (400) when calling the HeadBucket operation: Bad Request
```

Version: `stacker 1.3.0`

**Comment by phobologic** [comment]
Do you have any hooks in the config you're working with @behrangsa ?  The `aws_lambda` hook uses `ensure_cfn_bucket` as well, not sure if we have any capabilities of stopping hooks from kicking off during dump, but that'd still be a bug and something we should fix.

**Comment by behrangsa** [comment]
No, no hooks. To verify this, create a new account on your computer that doesn't have access to AWS -- or disconnect it from the Internet --, install stacker 1.3.0, create a minimal stack definition, and try dumping it into a file.

On OS X 10.11 at least, I get that error.

I might be able to create a screen recording later in the day and attach it here.

**Comment by behrangsa** [comment]
Here's the video recording: https://www.youtube.com/watch?v=9YDJVp2OQdg

With Stacker 1.2.0, when `-d ...` is present, no attempt is made to make AWS API calls.

With Stacker 1.3.0, even in the presence of `-d ...`, stacker tries to make AWS API calls.

**Comment by phobologic** [comment]
Sorry - I totally should have remembered this one.  This is fixed in master:

https://github.com/cloudtools/stacker/pull/594

Hoping to have a 1.4 release soon.
