### ISSUE TITLE
should we exit if stack is not exist?

### ISSUE THREAD

**Issue by ozbillwang** [cloudtools/stacker#627]
When run `stacker diff`, the stack is not exist, should we exit with error or continuously show the difference (should be all)?
 
```
$ stacker diff --region ap-southeast-2 --interactive conf/dev.env stacker.yaml
[2018-07-11T06:05:11] Using interactive AWS provider mode.
[2018-07-11T06:05:11] Diffing stacks: touch-nothing
[2018-07-11T06:05:11] Stack: "rds-dev-touch-nothing" does not exist in outputs or the lookup is not available in this stacker run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/stacker/plan.py", line 89, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/usr/local/lib/python2.7/dist-packages/stacker/actions/diff.py", line 218, in _diff_stack
    provider_stack = provider.get_stack(stack.fqn)
  File "/usr/local/lib/python2.7/dist-packages/stacker/providers/aws/default.py", line 519, in get_stack
    raise exceptions.StackDoesNotExist(stack_name)
StackDoesNotExist: Stack: "rds-dev-touch-nothing" does not exist in outputs or the lookup is not available in this stacker run
[2018-07-11T06:05:11] touch-nothing: failed (Stack: "rds-dev-touch-nothing" does not exist in outputs or the lookup is not available in this stacker run)
[2018-07-11T06:05:11] The following steps failed: touch-nothing
Makefile:15: recipe for target 'diff' failed
make: *** [diff] Error 1
```

related codes are here:

    def get_stack(self, stack_name, **kwargs):
        try:
            return self.cloudformation.describe_stacks(
                StackName=stack_name)['Stacks'][0]
        except botocore.exceptions.ClientError as e:
            if "does not exist" not in e.message:
                raise
            raise exceptions.StackDoesNotExist(stack_name)

**Comment by phobologic** [comment]
Diff is notoriously hard to work with when dealing with things like outputs.  The issue is that whenever a stack config references another stack using an output, but that stack doesn't exist, there's no way we can get a value (or even infer one).  This, unfortunately, means we can't diff any stack that uses an output referencing other stacks if those stacks don't exist - and since outputs are such a big/common part of stacker configs, not sure what the right thing is here.  We could just skip all stacks that fail like this when diffing (and give a simple error message), but not sure that'd make it that much better.
