### ISSUE TITLE
Stacker issue while updating the Cloudformation Stack 

### ISSUE THREAD

**Issue by sasiarjun** [cloudtools/stacker#686]
We are facing Stacker issue while updating the Cloudformation Stack after changing the value in the env file.  While updating the stack with the new value, the job fails with the below error.

Error:

Changes
- Modify ParameterStore (AWS::SSM::Parameter)
[2018-12-04T15:19:27] EOF when reading a line
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/plan.py", line 89, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/actions/build.py", line 311, in _launch_stack
    stack_policy=stack_policy,
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/providers/aws/default.py", line 798, in update_stack
    stack_policy=stack_policy, **kwargs)
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/providers/aws/default.py", line 838, in interactive_update_stack
    include_verbose=True,
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/providers/aws/default.py", line 148, in ask_for_approval
    '/'.join(approval_options)))
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/ui.py", line 48, in ask
    return get_raw_input(message)
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/ui.py", line 11, in get_raw_input
    return raw_input(message)
EOFError: EOF when reading a line
[2018-12-04T15:19:27] aws-dev-parameter-al-img changes:
Parameters Modified: KeyDescription, KeyValue

Changes:
- Modify ParameterStore (AWS::SSM::Parameter)
[2018-12-04T15:19:27] EOF when reading a line

Please help us to fix this.

**Comment by phobologic** [comment]
Looks like this was an issue with using Runway inside of CI/CD systems that didn't attach a terminal - Runway runs stacker in interactive mode, and so without a terminal there was no way to approve the changes.

(This was figured out by folks in the stacker slack channel: https://empirepaas.slack.com/archives/C08NMGJSH/p1544003933000500)

Closing!
