### ISSUE TITLE
stacker build -j 10 throws exception for all stacks

### ISSUE THREAD

**Issue by russellballestrini** [cloudtools/stacker#733]
Here is the error. `-j 10`

```
Exception in thread route53-main-zone:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/stacks/src/stacker/stacker/dag/__init__.py", line 468, in fn
    self.semaphore.acquire()
AttributeError: 'int' object has no attribute 'acquire'
```

CC @phobologic @ejholmes

**Comment by russellballestrini** [comment]
Maybe related: https://github.com/cloudtools/stacker/commit/a3feb4a85c815fc76cc6fe13b243a2655b497d03

**Comment by russellballestrini** [comment]
Upgrading to `stacker 1.7.0` fix this.
